# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_NGS_Tools.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1010, 766)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_bcl = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_bcl.setObjectName("pushButton_bcl")
        self.verticalLayout.addWidget(self.pushButton_bcl)
        self.pushButton_HDR = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_HDR.setObjectName("pushButton_HDR")
        self.verticalLayout.addWidget(self.pushButton_HDR)
        self.pushButton_BE = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_BE.setObjectName("pushButton_BE")
        self.verticalLayout.addWidget(self.pushButton_BE)
        self.pushButton_NHEJ = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_NHEJ.setObjectName("pushButton_NHEJ")
        self.verticalLayout.addWidget(self.pushButton_NHEJ)
        self.verticalLayout_2.addWidget(self.groupBox)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1010, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "请选择功能"))
        self.pushButton_bcl.setText(_translate("MainWindow", "BCL2Fastq"))
        self.pushButton_HDR.setText(_translate("MainWindow", "HDR or PE"))
        self.pushButton_BE.setText(_translate("MainWindow", "BE"))
        self.pushButton_NHEJ.setText(_translate("MainWindow", "NHEJ"))
